services:
  aiodi:
    build:
      context: .
      dockerfile: Containerfile
      target: py39
#      target: py310
#      target: py311
#      target: py312
    image: ghcr.io/aiopy/python-aiodi:py39-${VERSION:-latest}
#    image: ghcr.io/aiopy/python-aiodi:py310-${VERSION:-latest}
#    image: ghcr.io/aiopy/python-aiodi:py311-${VERSION:-latest}
#    image: ghcr.io/aiopy/python-aiodi:py312-${VERSION:-latest}
    volumes:
      - .:/app
