services:
  aiodi:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: ghcr.io/aiopy/python-aiodi:${VERSION:-latest}
    volumes:
      - .:/app

version: "3.7"
